using Microsoft.EntityFrameworkCore;
using SMS.Microservices.NotificationMessaging.Models;

namespace SMS.Microservices.NotificationMessaging.Data;

public class NotificationMessagingDbContext : DbContext
{
    public NotificationMessagingDbContext(DbContextOptions<NotificationMessagingDbContext> options) : base(options)
    {
    }

    public DbSet<Message> Messages { get; set; }
    public DbSet<Notification> Notifications { get; set; }
    public DbSet<Announcement> Announcements { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Configure ExternalId to be generated by the application code (Guid.NewGuid() in model constructors)
    }

    public override int SaveChanges()
    {
        AddTimestamps();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        AddTimestamps();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void AddTimestamps()
    {
        var entities = ChangeTracker.Entries()
            .Where(x => x.Entity is not null && (x.State == EntityState.Added || x.State == EntityState.Modified));

        // TODO: Replace with actual user ID from authentication context
        var currentUserId = 1; 

        foreach (var entity in entities)
        {
            if (entity.State == EntityState.Added)
            {
                if (entity.Entity.GetType().GetProperty("CreatedAt") != null)
                {
                    entity.Property("CreatedAt").CurrentValue = DateTime.UtcNow;
                }
                if (entity.Entity.GetType().GetProperty("CreatedBy") != null)
                {
                    entity.Property("CreatedBy").CurrentValue = currentUserId;
                }
            }

            if (entity.Entity.GetType().GetProperty("UpdatedAt") != null)
            {
                entity.Property("UpdatedAt").CurrentValue = DateTime.UtcNow;
            }
            if (entity.Entity.GetType().GetProperty("UpdatedBy") != null)
            {
                entity.Property("UpdatedBy").CurrentValue = currentUserId;
            }
        }
    }
}
